### ISSUE TITLE
 Request to Update MTEB Leaderboard with New Model Scores

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/leaderboard#19]
Originally posted here: https://huggingface.co/spaces/mteb/leaderboard/discussions/136

> Dear MTEB Team,
> 
> We have recently submitted the performance scores for two new embedding models, which can be viewed at the following URLs:
> https://huggingface.co/BAAI/bge-en-icl
> https://huggingface.co/BAAI/bge-multilingual-gemma2
> 
> We see that the model results do not seem to have refreshed. Would you mind updating the MTEB leaderboard to include these new submissions, please?
> 
> Thank you for your assistance!

**Comment by KennethEnevoldsen** [comment]
Dear [@cfli](https://huggingface.co/cfli),

It seems like we ran an [automatic update](https://github.com/embeddings-benchmark/leaderboard/actions) a few hours ago.

Where it indeed seems to have fetched the data as intended:

> Fetching 'BAAI/bge-en-icl' metadata:  99%|█████████▉| 1283/1290 [04:59<00:04,  1.44it/s]                                    
> Fetching 'BAAI/bge-en-icl' metadata: 100%|█████████▉| 1284/1290 [05:00<00:03,  1.65it/s]


However, it still does not appear on the benchmark. Will take a closer look at this

**Comment by KennethEnevoldsen** [comment]
digging a bit deeper it seems to be due to:

https://github.com/embeddings-benchmark/leaderboard/blob/1fd4bba12b863c5ad55010f6dc01ffb0f26f892f/refresh.py#L272

Which returns an empty list. This seems to be caused by you having none of the the tasks for the specific board (which you don't so that is to be expected), however, it seems like we only go over one board due to:

https://github.com/embeddings-benchmark/leaderboard/blob/1fd4bba12b863c5ad55010f6dc01ffb0f26f892f/refresh.py#L411-L412

Which probably should be commented out. Will add a PR

**Comment by 545999961** [comment]
Alright. Thank you very much for the assistance you've provided.
