### ISSUE TITLE
Add MedEmbed

### ISSUE THREAD

**Issue by abhinand5** [embeddings-benchmark/leaderboard#55]
Can you please add [abhinand/MedEmbed-small-v0.1](https://huggingface.co/abhinand/MedEmbed-small-v0.1)? I can't find the model on the leaderboard even after the refresh.

I followed the steps [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md) and created a model card.

Let me know if I'm missing something or I just need to wait another day.

**Comment by Samoed** [comment]
Leaderboard is updating daily. You need to wait a bit

**Comment by abhinand5** [comment]
It was actually there, just didn't show up in search! Thanks!

**Comment by Samoed** [comment]
Leadeboard updated 4 hours ago and your model showed
