### ISSUE TITLE
Fix models with empty results

### ISSUE THREAD

**Issue by orionw** [embeddings-benchmark/leaderboard#8]
Both [NV-Retriever](https://huggingface.co/nvidia/NV-Retriever-v1) and [E5-R-Mistral-7B](https://huggingface.co/BeastyZ/e5-R-mistral-7b) show up with empty results.

**Comment by orionw** [comment]
I was wrong, NV-Retriever is now on the leaderboard, it just only has Retrieval results. 

![image](https://github.com/embeddings-benchmark/leaderboard/assets/31665361/b5dd0242-196b-4b82-8305-4349f9f9906a)

E5-r-mistral is not showing up fully because of CQADupstackRetrieval

![image](https://github.com/embeddings-benchmark/leaderboard/assets/31665361/9ebac1bb-ad22-45e5-9878-5dcc7a3e0025)

**Comment by orionw** [comment]
cc'ing @BeastyZ as an FYI, although it appears that the metadata is right. Is that correct @KennethEnevoldsen?

**Comment by bschifferer** [comment]
@orionw can you explain how the Model Size and Memory is populated? I looked at README.md of other models, but I did not find any metadata related to it

**Comment by orionw** [comment]
@bschifferer that's in our [model_meta.yaml](https://github.com/embeddings-benchmark/leaderboard/blob/main/model_meta.yaml#L2) folder, we don't currently have an automatic way of doing that. If you want to add yours that would be awesome! Or just let me know here. Thanks for the reminder for us to add that to the documentation.

**Comment by rnyak** [comment]
@orionw hello! Thanks for guiding us. I added this [PR](https://github.com/embeddings-benchmark/leaderboard/pull/9), would you mind please reviewing. Please let us know if we need to do anything else.

**Comment by rnyak** [comment]
@bschifferer for viz.

**Comment by KennethEnevoldsen** [comment]
> cc @KennethEnevoldsen  @orionweller This is regarding the PawsXPairClassification (fr) key not being found.

Will take a look at this issue tomorrow. 

Re. CQADupstackRetrieval seems like it is an aggregate score across a few tasks. We can add that to the create_meta CLI or directly to the leaderboard. Seems like previously it has been in the frontmatter on the .md so create_meta is probably the best option.

**Comment by orionw** [comment]
Thanks @KennethEnevoldsen. Yes, @BeastyZ we have [a script for this in mteb](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/merge_cqadupstack.py)

**Comment by BeastyZ** [comment]
Thanks @orionw. I got the score of CQADupstackRetrieval with your [script](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/merge_cqadupstack.py). I have updated the Model Card of e5-R-mistral-7b. Could you refresh the space now or let me know the next scheduled refresh time?

**Comment by orionw** [comment]
Thanks @BeastyZ! It refreshes once a day or on commit to `main`. I just made a small PR for another change so you should see updates soon when it finishes refreshing.

**Comment by orionw** [comment]
Looks like both models are on the leaderboard. Closing the issue

**Comment by BeastyZ** [comment]
@rnyak @bschifferer @KennethEnevoldsen @orionw @guenthermi 
I am truly grateful for your help!

**Comment by tomaarsen** [comment]
> @orionw can you explain how the Model Size and Memory is populated? I looked at README.md of other models, but I did not find any metadata related to it



> @bschifferer that's in our [model_meta.yaml](https://github.com/embeddings-benchmark/leaderboard/blob/main/model_meta.yaml?rgh-link-date=2024-07-11T17%3A03%3A28Z#L2) folder, we don't currently have an automatic way of doing that. If you want to add yours that would be awesome! Or just let me know here. Thanks for the reminder for us to add that to the documentation.


Model Size and Memory are automatically computed via https://github.com/embeddings-benchmark/leaderboard/blob/main/utils/model_size.py#L12. This method looks at the `safetensors`/`pytorch_model.bin` file in your repository, so it will be blank until you've released the model.
An alternative is indeed via the [model_meta.yaml](https://github.com/embeddings-benchmark/leaderboard/blob/main/model_meta.yaml?rgh-link-date=2024-07-11T17%3A03%3A28Z#L2) file, but this was primarily for proprietary models that aren't on Hugging Face/don't have metadata on HF. I see that NV-Retriever-v1 has also been added via #9, which will work fine. 

- Tom Aarsen

**Comment by orionw** [comment]
Thanks @tomaarsen for the clarification.  Glad to see I was wrong :)

**Comment by KennethEnevoldsen** [comment]
For future reference: I have added a [fix](https://github.com/embeddings-benchmark/mteb/pull/1079) to include CQADupstackRetrieval in future version using `mteb create_meta`

@orionw has also fixed the PawsXPairClassification issue. This should hopefully make leaderboard addition easier in the future
